### ISSUE TITLE
Using with gamescope/multiple environment values?

### ISSUE THREAD

**Issue by fenglengshun** [evg-zhabotinsky/libspeedhack#6]
I often play games on gamescope to avoid compositor issues, as well as needing to set multiple environment variables for Japanese games. So my command often looks like this: `gamescope -- env LC=LC_ALL=ja_JP.UTF-8 LANG=ja_JP.UTF-8 TZ=Asia/Tokyo WINEPREFIX=/home/fenglengshun/Storage/Data/Apps/x/wine/winejp WINEARCH=win32 wine './Game.exe'`

Where should I put `speedhack` in so that it works properly?

**Comment by evg-zhabotinsky** [comment]
Right before `env` or `wine`, either way should work the same. The script only sets up LD_PRELOAD and LD_LIBRARY_PATH env vars and creates the control pipe.
As for "workling properly", YMMV. I played a game on Wine (Witch's house) where only animation speed was affected, but not game speed.

**Comment by evg-zhabotinsky** [comment]
Note:
Placing `speedhack` before `gamescope` would also affect gamescope itself, which you probably don't want.
Also, due to current control pipe implementation, running multiple processes with libspeedhack results in undefined behavior.

Placing it before `env` would affect env too, but it's okay; because env "dies" after setting up environment (runs program with `exec()`). Simple wrappers/launchers (env, primusrun/prime-run, most bash scripts) usually work fine, so long as they "terminate" before running game, "hang" while game is running, or never query time.

**Comment by fenglengshun** [comment]
Hm, I'm not sure why but I got an error `ERROR: ld.so: object 'libspeedhack.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

**Comment by Milk-Cool** [comment]
> Hm, I'm not sure why but I got an error `ERROR: ld.so: object 'libspeedhack.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

do you have the eset nod32 antivirus?

**Comment by evg-zhabotinsky** [comment]
> Hm, I'm not sure why but I got an error `ERROR: ld.so: object 'libspeedhack.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

You probably need to do `make multilib` instead of just `make` ( = `make native`), since the game is 32-bit. Building 32-bit library on 64-bit system is x86-specific and requites extra build tools, so I disabled it by default. See README / How to build.

**Comment by fenglengshun** [comment]
Ah, I think the issue was that `fish` on Garuda breaking things as usual (right after my first post I accidentally broke my install, experimenting vfio and switched to Garuda to try it out).

Went to bash and zsh, it was mostly fine, though it only affects the game's music. Not sure why, given that last time I tried it on Manjaro from an AUR install, everything was fine. This time I manually `make` the lib files but it was only affecting the wrong thing.

Regardless, that's a different issue entirely, and honestly Garuda is just a mess that I don't know or want to untangle it, much less want to make things harder on you when the problem is probably Garuda and/or their sh profile files. Thanks.
